export const mockApplicationStatus = [
  {
    applicationNo: "1001",
    zone: "Zone 1",
    zoneEmpId: 101,
    campus: "Campus A",
    campusId: 600,
    pro: "John Doe",
    proId: 201,
    dgm: "Jane Smith",
    dgmEmpId: 301,
    status: "Sold",
    statusId: 1,
    reason: "",
    isSelected: false,
  },
  {
    applicationNo: "1002",
    zone: "Zone 2",
    zoneEmpId: 102,
    campus: "Campus B",
    campusId: 601,
    pro: "Ali Khan",
    proId: 202,
    dgm: "Sara Lee",
    dgmEmpId: 302,
    status: "Available",
    statusId: 2,
    reason: "",
    isSelected: false,
  },
  {
    applicationNo: "1003",
    zone: "Zone 1",
    zoneEmpId: 101,
    campus: "Campus A",
    campusId: 600,
    pro: "Vikram Singh",
    proId: 203,
    dgm: "Priya Sharma",
    dgmEmpId: 303,
    status: "Damaged",
    statusId: 3,
    reason: "Incorrect details",
    isSelected: true,
  },
  {
    applicationNo: "1004",
    zone: "Zone 3",
    zoneEmpId: 103,
    campus: "Campus C",
    campusId: 602,
    pro: "Ravi Kumar",
    proId: 204,
    dgm: "Naveen Joshi",
    dgmEmpId: 304,
    status: "Confirmed",
    statusId: 4,
    reason: "",
    isSelected: false,
  },
  {
    applicationNo: "1005",
    zone: "Zone 2",
    zoneEmpId: 102,
    campus: "Campus B",
    campusId: 601,
    pro: "Priya Sharma",
    proId: 205,
    dgm: "Vikram Singh",
    dgmEmpId: 305,
    status: "Issued",
    statusId: 5,
    reason: "",
    isSelected: false,
  },
  {
    applicationNo: "APP1006",
    zone: "Zone 1",
    zoneEmpId: 101,
    campus: "Campus A",
    campusId: 600,
    pro: "John Doe",
    proId: 201,
    dgm: "Jane Smith",
    dgmEmpId: 301,
    status: "Unavailable",
    statusId: 6,
    reason: "Pending documents",
    isSelected: false,
  },
];